### ISSUE TITLE
pstoreprobe 100% CPU

### ISSUE THREAD

**Issue by paulrouget** [clearlinux/telemetrics-client#115]
Not sure if this is the right repo.

Running clearlinux via the Clear Linux OS Desktop Live USB. CPU is going full speed. I have to kill `pstoreprobe` which takes 100% of the CPU.

**Comment by alexjch** [comment]
This is the right repo, thanks for reporting this issue. I'm trying to reproduce.

**Comment by alexjch** [comment]
Following this [instructions](https://clearlinux.org/documentation/clear-linux/get-started/bootable-usb#bootable-usb-linux) with image `clear-30140-live-desktop.img` I was unable to reproduce this issue. @paulrouget can you share some information about running environment? (vm, laptop, desktop, etc) thanks again.

**Comment by paulrouget** [comment]
GPD Pocket 2:

Processor | Intel Core M3-8100Y, up to 3.4GHz
GPU | Intel UHD Graphics 615, up to 900MHz
RAM | 8GB LPDDR3 dual channel
Storage | 128GB
WiFi | 802.11 a/ac/b/g/n, 2.4G/5G dual band WiFi, transmission rate up to 867Mbps
Bluetooth Version | 4.1
Interface | 2 x USB, 1 x USB-C, 3.5mm, microphone, microSDXC
Battery | Battery Type: Li-Polymer; Battery Capacity: 6800mAhBattery Life: About 6-8 hours (depend on actual working conditions)
4K | Support
HDMI | 4096 x 2304 @ 24Hz

I have a running instance of Clealinux on that device, but with telemetry disabled. I'd be happy to help run some tests if needed.

**Comment by alexjch** [comment]
Fix in Version 2.2.1 [commit](https://github.com/clearlinux/telemetrics-client/commit/e19e72a5b30ad31fe1b389b2e6c480179aa93a1e).
