### ISSUE TITLE
/usr/bin/telem_update does not have the right permissions

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/telemetrics-client#163]
In build 31130, file /usr/bin/telem_update does not have right permissions

bbt-worker@clr-installer-gui~ $ swupd info
Distribution:      Clear Linux OS
Installed version: 31130
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
bbt-worker@clr-installer-gui~ $ stat -c "%a %n" /usr/bin/telem_update
544 /usr/bin/telem_update
bbt-worker@clr-installer-gui~ $ ls -l /usr/bin/telem_update
-r-xr--r-- 1 root root 683 Sep 27 16:40 /usr/bin/telem_update
bbt-worker@clr-installer-gui~ $

**Comment by alexjch** [comment]
@arturo-garcia-garcia, thanks for reporting this.  `/usr/bin/telem_update` is not present in the source. This is part of the packaging specific for CL I will adjust permissions accordingly in packaging code. I'm closing the issue here, since this file is not present in this repo.
