### ISSUE TITLE
bert-probe.service fails at every boot

### ISSUE THREAD

**Issue by JSEHV** [clearlinux/telemetrics-client#170]
The bert-probe.service fails at every boot, with an error message:

```
12:01 PM bert-probe.service: Failed with result 'exit-code'.
12:01 PM bert-probe.service: Main process exited, code=exited, status=1/FAILURE
12:01 PM Failed to read payload from: /sys/firmware/acpi/tables/data/BERT
12:01 PM Started Telemetrics BERT Probe.
```

**Comment by ahkok** [comment]
@alexjch looking at the code I can't explain this, unless the permissions on `/sys/firmware/acpi/tables/data/BERT` are such that the user `telemetry` can't access the file.

@JSEHV can you perhaps run `ls -ld /sys/firmware/acpi/tables/data/BERT` ?

**Comment by ahkok** [comment]
Or `nc_b64enc_filename()` fails to execute...

**Comment by jurobystricky** [comment]
Looking at the code, it seem the probe fails if the payload does not fit in payload buffer (4k).

**Comment by jurobystricky** [comment]
Looking at one system with BERT file present, one can see several problems:
<pre>
ls -al /sys/firmware/acpi/tables/data/BERT
-r-------- 1 root root 32768 Nov 20 09:34 /sys/firmware/acpi/tables/data/BERT
</pre>

1. Only root can read the file, however bert-probe service runs as user "telemetry"
2. The file size is 32k, well above MAX_PAYLOAD (4k).

Both of those would cause the service to fail with:
<pre>
PM bert-probe.service: Failed with result 'exit-code'.
</pre>

3. Inspecting the file shows it is completely empty (filled with 0x00). This can be most likely interpreted as no error, based on the first 32 bits description:
<pre>

Block Status | 4 | 0 | Indicates to the OS what kind of error information is reported in the error packet: 		 				
Bit 0 – Uncorrectable Error Valid: If set to one, indicates 	that an uncorrectable error condition exists. 				 				
Bit 1 – Correctable Error Valid: If set to one, indicates that a correctable error condition exists. 				 				
Bit 2 – Multiple Uncorrectable Errors: If set to one, indicates	that more than one uncorrectable errors have been detected.
Bit 3 – Multiple Correctable Errors: If set to one, indicates that more than one correctable errors have been detected. 				 				
Bit 4–13 – Error Data Entry Count: This value indicates the number of Error Data Entries found in the Data section. 				 				
Bit 14–31 – Reserved.
-- | -- | -- | --
</pre>

**Comment by ahkok** [comment]
It appears to me that the core design of the probe needs to be revisited. The probe should not create errors if there is no error, and those bit states suggest that there isn't any.

I'm not sure how we want to handle payloads over 4k, but, I don't think we want to send more than the first 32 bits anyway? What kind of error messages are we going to encounter in the rest of the data here?

**Comment by jurobystricky** [comment]
Agreed. The blocks are described here:
https://uefi.org/sites/default/files/resources/ACPI%206_2_A_Sept29.pdf#G23.1355868
There is another BERT related file  /sys/firmware/acpi/tables/BERT
The probe does not care about this one. I did look at it, it is correct (checksum an signature). Unfortunately, it also says the error region size is 32k, so not much of a help there.

**Comment by jurobystricky** [comment]
I am having some second thoughts. It appears that kernel also parses BERT tables:

https://elixir.bootlin.com/linux/v5.3.12/source/drivers/acpi/apei/bert.c

and nicely displays parsed info via printk/dmesg:
https://elixir.bootlin.com/linux/v5.3.12/source/drivers/firmware/efi/cper.c#L513

 So perhaps a better way would be to modify bertprobe code and parse kernel messages for "BERT:" or remove the bertprobe entirely and report BERT issues via the existing kernelprobe. One way or another, the challenge is to test the resulting code, due to the lack of BERT  reproducers.

**Comment by jurobystricky** [comment]
The release 2.3.2 https://github.com/clearlinux/telemetrics-client/releases/tag/v2.3.2 removed the bert-probe completely and moved the original functionality of bert-probe to klogscanner.  The new klogscanner was successfully tested with a BERT reproducer.
Hence this issue can be closed.
