### ISSUE TITLE
Forbid multiple instances of 'telemd' running with same configuration

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/telemetrics-client#34]
Multiple running instances of telemetrics daemon (telemd) are not supported when they use the same socket path and spool directory (as defined in telemetrics.conf). The daemon should exit if it detects an existing instance that matches its own configuration.

**Comment by alexjch** [comment]
Are multiple instances of the daemon a valid use case? or is this a feature to protect operator from himself?

**Comment by phmccarty** [comment]
Multiple instances, each with different configurations, is possible. When they have the same configuration, it's not supported, so I would like to see error handling added for this case.

**Comment by phmccarty** [comment]
Thinking about this more, I wonder if we should lock down the telemetry socket to only be readable by the telemetry daemon that first opens it. So, enforcing a one reader, multiple writers model. Then checking for multiple instances would not be required, because a second attempt to open the socket for reading would fail with an error by design.

**Comment by rnesius** [comment]
Only one process can bind to the socket at a time I think.  After the first daemon runs the rest will fail to bind.

**Comment by alexjch** [comment]
This happens only during development when the user (developer) is running probes and daemon while there's a telemetry instance already installed in the system. What @rnesius mentions is correct.
