### ISSUE TITLE
Support default telemd default configuration values in the binary

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/telemetrics-client#38]
Instead of requiring that `telemetrics.conf` exist and contain all key/value pairs to instantiate telemd configuration, I propose that the default values be baked into the binary.

Then the values in `/usr/share/defaults/telemetrics/telemetrics.conf` could reflect the hardcoded defaults, and the values in `/etc/telemetrics/telemetrics.conf` would override the defaults.

A nice side effect of this change is that `/etc/telemetrics/telemetrics.conf` would not need to contain *all* configuration values, just the values that should be overridden.

**Comment by jurobystricky** [comment]
Implemented in the commit "configuration: rework to allow layered configuration".
