### ISSUE TITLE
telemd does not print an error message when telemetrics.conf is missing key/values

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/telemetrics-client#39]
Currently, if telemd fails with an error due to missing key/value pairs in telemetrics.conf, it does not print an error message. It should print an error message for this condition.

**Comment by phmccarty** [comment]
An example:

```
# sed -i '/^daemon_recycling_enabled/d' /etc/telemetrics/telemetrics.conf
# telemd
# echo $?
1
```

**Comment by jurobystricky** [comment]
After the commit "configuration: rework to allow layered configuration" it is only necessary to enter key/value pairs to override any built-in default values. In other words,  missing key/value pairs from telemetrics.conf should not generate errors.
