### ISSUE TITLE
Unclear from usage message which parameters require options

### ISSUE THREAD

**Issue by bwarden** [clearlinux/telemetrics-client#57]
https://github.com/clearlinux/telemetrics-client/blob/d75e27a5c4d1316708019bf77fdbd6b5b6dead6d/src/journal/cli.c#L30

It is unclear to me from this usage message which options require an argument, and which ones are simple flags.

**Comment by jurobystricky** [comment]
Closing, as the usage screen was improved, showing optional arguments:

**printf("  telem_journal [-Vi] [-r <record_id>] [-e <event_id>] [-c <classification>] [-b <boot_id>]\n\n");**


https://github.com/clearlinux/telemetrics-client/blob/master/src/journal/cli.c
