### ISSUE TITLE
No detail on data collected by default

### ISSUE THREAD

**Issue by effndc** [clearlinux/telemetrics-client#58]
There is no documentation for what telemetry data is included by default or path of extending to include additional error types.  Please provide documentation on what data telemetrics-client actually collects and forwards.

**Comment by alexjch** [comment]
There's metadata (arch details mostly) and specific data collected by probes. I will update you when documentation is provided.

**Comment by alexjch** [comment]
Added general information about probes https://github.com/clearlinux/telemetrics-client/blob/master/src/probes/README.md

**Comment by alexjch** [comment]
Documentation was added, closing this issue.
