### ISSUE TITLE
Add configuration documentation

### ISSUE THREAD

**Issue by effndc** [clearlinux/telemetrics-client#60]
The current documentation is not clear or fully comprehensive on the steps required to install and use the telemetrics-client, e.g. current documentation fails to mention that a special account named "telemetry" must be created before proceeding with all of the configuration steps.

I would expect this to be validated and adjusted for accuracy, but something similar to:

1. Install patched MCElog (if MCE reporting is desired) 
    a. erase existing install if present:
    rpm --erase mcelog

    b. install patched mcelog

    c.  Enable mcelog:
    systemctl enable mcelog.service

    d.  Edit service start script and fix path for mcelog binary in /usr/lib/systemd/system/mcelog.service:
    e.  Reload systemd: systemctl daemon-reload
    f.  Start MCElog: systemctl start mcelog.service

2.  Make & Install Clear Telemetry
    a.  Make config directory: mkdir /etc/telemetrics/
    b.  Copy /usr/share/defaults/telemetrics/telemetrics.conf to /etc/telemetrics/
    c.  Edit /etc/telemetrics/telemetrics.conf to define target telemetrics-backend server
    d.  Create user:  
    useradd -r -M telemetry -s /sbin/nologin -c "Clear Telemetry"

    e.  Create spool directory 
    mkdir -p /var/spool/telemetry
    
    f.  Set permissions on spool 
    chown -R telemetry:telemetry /var/spool/telemetry
    
    g.  Set MachineID: https://github.com/clearlinux/telemetrics-client#machine-id
    example: hostname -s > /etc/telemetrics/opt-in-static-machine-id
    
    h.  Enable services: systemctl enable telemd.socket telemd.path
    i.  Start services systemctl start telemd.socket telemd.path

**Comment by alexjch** [comment]
This is highly targeted to MCE and MCE patching I don't believe this should be part of the core telemetry source.
