### ISSUE TITLE
telemd delivery retries 

### ISSUE THREAD

**Issue by ahkok** [clearlinux/telemetrics-client#64]
User reported issue:

at boot time, telemd starts due to socket activation, and may fail due to inoperable DNS. Events remain stored up to an hour or so before final delivery is successful.

What needs to happen is that the requests should be retried in a reasonable fashion for a reasonable period (e.g. after 1, 2, 4, 8, 16 and 32 seconds) before giving up.

**Comment by ahkok** [comment]
`src/spool.c:130` seems wrong, and I don't see other retries at a higher level.

**Comment by alexjch** [comment]
Closing this since this feature was implemented in version 2
