### ISSUE TITLE
services not restarted

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/telemetrics-client#83]
After a fresh boot, all probes work as advertised.

<pre>
$ systemctl | grep probe
  swupd-probe.path                                     loaded active waiting   swupd telemetry probe                                             
  journal-probe.service                                loaded active running   Telemetrics Systemd Journal Probe                                 
  oops-probe.service                                   loaded active running   Telemetrics Kernel Oops Probe      
  hprobe.timer                                
</pre>

But after restarting telemtrics, either by 
<pre>
sudo telemctl stop
sudo telemctl start
</pre>

or 
<pre>
sudo telemct opt-out
sudo telemctl opt-in
</pre>

or 
<pre>
sudo telemctl restart
</pre>

some services/probes are not running:
<pre>
$ systemctl | grep probe                                                                                                                                                   
  swupd-probe.path                                     loaded active waiting   swupd telemetry probe                                                            
  hprobe.timer 
</pre>

As you see, only hprobe.timer is restarted. (swupd-probe is not handled by telemctl). In other words, after restarting telemtrics, some probes remain disabled. After restarting the telemetrics one would expect the same state of telemtrics services as after rebooting.

**Comment by alexjch** [comment]
Working on fix thanks for reporting I will submit PR.

**Comment by alexjch** [comment]
Closed issue accidentally please take a look.

**Comment by jurobystricky** [comment]
works fine now
