### ISSUE TITLE
journalprobe: telemetry opt-out/opt-in results in resending data to backend

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/telemetrics-client#87]
Each time user opts-out and then opts-in from telemetry again (or restarts telemetry), the journal is parsed again and the same data is being sent to the backend again. This can actually be quite a lot of messages each time (about a dozen last time I tested). So I see several problems with this:
1. Same data re-sent again, spamming the backend
2. Any statistics done by the backend are skewed (same problems reported multiple time)
3. Privacy: if user opts out, then the user does not want data to be reported. After the user opts-in, reporting is allowed. However, this re-enabled reporting will also report data from the period the user was opted-out.

**Comment by alexjch** [comment]
I have not seen the journal probe code lately, but I see how this could happen. **Pure speculation** we can use current time to mitigate reporting journal logs twice, but at the same time how often does this happen (opt-in / opt-out). On the other hand reporting logs during a time that telemetry was opt'ed'-out is a problem.

**Comment by jurobystricky** [comment]
The code parses the log first (probe sending messages as needed) and then sits and waits for new log entries. So the fix seems easy, just remove the initial parsing. But that way we can also miss some events that occurred between boot and before (enabled & opted-in) telemetry services started.

**Comment by jurobystricky** [comment]
This has been fixed by 
https://github.com/clearlinux/telemetrics-client/commit/4b777f71f71db7adf6ba23d83767348b051684ee
