### ISSUE TITLE
First log goes lost

### ISSUE THREAD

**Issue by thkukuk** [clearlinux/telemetrics-client#97]
I'm using telemetrics-client (current git) on openSUSE Tumbleweed with systemd 239, but this should not matter.

I'm using the following configuration:
record_server_delivery_enabled=false
record_retention_enabled=true

If I enable telempostd.path, the first telemetry entry send will go lost. All later entries will end in the journal, until telempostd stops. After that, the first entry will go lost again.

Howo reproduce:
- Adjust configuration to log only local
- telemctl start (so telempostd.path will be used)
- Create an entry with telem-record-gen
- telem_journal -V will not show a new entry.
- Create a new entry with telem-record-gen a second time
- telem_journal -V will show the new entry
- Call systemctl telempostd.service to stop telempostd
- Call telem-record-gen, no new entry will be created
- Call repeatedly telem-record-gen, all entries will end in the jorunal and telem_journal -V will show them.

**Comment by alexjch** [comment]
Thanks for the details report I'm taking a look at this.

**Comment by jurobystricky** [comment]
It is easy to reproduce by:
<pre>
$ sudo telemctl restart
$ hprobe
</pre>
Note there is no new entry in the journal. Incidentally, there is also no record stored even if "record_retention_enabled=true" either.
It is only the first log entry/saved record that misbehave, all subsequent probes work properly.

**Comment by alexjch** [comment]
Fixed in commit f4f012af7b3bf3f5d204c75a05a461ce24733724
